project_name: ork
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.GitCommit={{.Env.GITHUB_SHA}} -X main.OrkVersion={{.Env.GITHUB_REF_NAME}}

nfpms:
  -
    vendor: Kyriakos Kentzoglanakis
    license: MIT
    homepage: https://github.com/kkentzo/ork
    maintainer: kkentzo @ github
    description: |-
      Workflow management for software projects

    formats:
      - apk
      - deb
      - rpm
