name: test

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
      -
        name: Install Go
        uses: actions/setup-go@v2
      -
        name: Test
        run: go run . test
